version: '3'
services:
  jenkins:
    container_name: lilouchsjenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host-image
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh/command.sh:/tmp/command.sh
    networks:
      - net

  remote_host2:
    container_name: remote-host2
    image: remote-host-image
    volumes:
      - $PWD/remoteHost2.sh:/tmp/remoteHost2
    networks:
      - net


  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
  jenkins_ansible:
    container_name: jenkins-ansible
    image: jenkins-ansible-image
    build:
      context: jenkinsAnsible
    volumes:
      - $PWD/jenkins_ansible_home:/var/jenkins_ansible_home
    ports:
      - "2222:8080"
    networks:
      - net
networks:
  net:
