version: '3'
services:

  jenkins_ansible:
    container_name: jenkins-ansible
    image: jenkins-ansible-image
    build:
      context: jenkinsAnsible
    volumes:
      - $PWD/jenkins_ansible_home:/var/jenkins_ansible_home
    ports:
      - "2222:8080"
    networks:
      - net

  remote_host:
    container_name: remote-host
    image: remote-host-image
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh/command.sh:/tmp/command.sh
    networks:
      - net
networks:
  net:
