version: '3'
services:

  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
  jenkins_ansible:
    container_name: jenkins-ansible
    image: jenkins-ansible-image
    build:
      context: jenkinsAnsible
    volumes:
      - $PWD/jenkins_ansible_home:/var/jenkins_ansible_home
    ports:
      - "2222:8080"
    networks:
      - net

  web:
    container_name: web
    image: ansible-web
    build:
      context: jenkins_ansible_home/web
    ports:
      - "80:80"
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host-image
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh/command.sh:/tmp/command.sh
    networks:
      - net

networks:
  net:
